---
title: "Rmd File"
author: "Emily Daubenspeck"
date: "November 14, 2018"
output: pdf_document
---

## Instructions

*Make at least 5 images of your data, noting what you have learned about your data as a result of creating these images

*Create numerical summaries for at least 4 variables in your dataset. 

*What did you learn about your data as a result of creating these summaries?

Attempt to implement at least 3 versions of your team's highest priority method as outlined in the revised proposal. This could look like:

If you are focusing on regression, you could:
Run a few bivariate regression models
Try a few subset selection methods
Experiment with ridge regression and lasso

If you are prioritizing classification, you could try kNN, QDA, LDA, and Logistic regression (and comparing the assumptions violated in each)
If your plan was to do classification and then regression, could the class on November 12 provide inspiration?
Leverage cross-validation with different number of folds to tune various hyper-parameters (such as penalties or the k in kNN).

```{r, message = FALSE, warning = FALSE}

```
